import React, { useContext, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Images from 'next/image'
import Link from 'next/link'
// import { DownOutlined, UserOutlined } from '@ant-design/icons'
// import MyContext from '../../../lib/context'
// import zhCN from 'antd/lib/locale/zh_CN'
// import './index.css'

const App = (props = {}) => {
  const { children, tab } = props
  //   const { user } = useContext(MyContext)
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>金翁农业</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <header>
        {/* <div className="header">
          <div className="header-main">广告</div>
        </div> */}
        <div className="nav">
          <div className="nav-main">
            <a href="" className="logo"></a>
            <Link href="/">
              <a href="" className="nav-item">
                商品
              </a>
            </Link>
            <Link href="/">
              <a href="" className="nav-item">
                甜瓜
              </a>
            </Link>
            <Link href="/">
              <a href="" className="nav-item">
                冬枣
              </a>
            </Link>
            {/* <a href="" className="nav-item">
              iPad
            </a>
            <a href="" className="nav-item">
              iPhone
            </a>
            <a href="" className="nav-item">
              Watch
            </a>
            <a href="" className="nav-item">
              Music
            </a>
            <a href="" className="nav-item">
              技术支持
            </a> */}
            <div className="search"></div>
            <div className="shop-bag"></div>
          </div>
          <div className="nav-mobile">
            <input
              type="checkbox"
              name=""
              id="menu-check"
              value=""
              style={{ display: 'none' }}
            />
            <label href="" className="mobile-list" htmlFor="menu-check">
              <div className="line"></div>
              <div className="line"></div>
            </label>
            <a href="" className="logo"></a>
            <a href="" className="shop-bag"></a>
            <div className="menu">
              <div className="searchInput">
                <span className="icon"></span>
                <span className="input">搜索</span>
              </div>
              <div className="menulist">
                <Link href="/">
                  <a href="" className="menu-item">
                    商品
                  </a>
                </Link>
                <Link href="/">
                  <a href="" className="menu-item">
                    甜瓜
                  </a>
                </Link>
                <Link href="/">
                  <a href="" className="menu-item">
                    冬枣
                  </a>
                </Link>
                {/* <a href="" className="menu-item">
                  iPad
                </a>
                <a href="" className="menu-item">
                  iPhone
                </a>
                <a href="" className="menu-item">
                  Watch
                </a>
                <a href="" className="menu-item">
                  Music
                </a>
                <a href="" className="menu-item">
                  技术支持
                </a> */}
              </div>
            </div>
          </div>
        </div>
      </header>
      <main>
        {/* <div className="ad">
          <div className="buylink">
            <a href="https://www.apple.com.cn/shop">在线选购</a>
          </div>
          <div className="ad-text">
            ，享受免费送货、Specialist 专家支持、免息分期等服务。
          </div>
        </div> */}
        <div className="goods" id="iPhone12">
          <div className="goods-name">金翁农业</div>
          <div className="goods-advantage">中国知名农产品供应商</div>
          {/* <div className="price-introduction">
            <div>RMB 229/月或 RMB 5499 起，</div>
            <div className="introduce">
              还可折抵换购<span className="shangbiao">1</span>
            </div>
          </div> */}
          <div className="buy-link">
            <a
              className="buy-link-text"
              //   href="https://www.apple.com.cn/iphone-12/"
            >
              进一步了解
            </a>
            <a
            // href="https://www.apple.com.cn/iphone-12/"
            >
              <div className="jiantou"></div>
            </a>
            <a
              className="buy-link-text"
              //   href="https://www.apple.com.cn/shop/buy-iphone/iphone-12"
            >
              购买
            </a>
            <a
            // href="https://www.apple.com.cn/shop/buy-iphone/iphone-12"
            >
              <div className="jiantou"></div>
            </a>
          </div>
        </div>
        {/* <div className="goods" id="iphone12-pro">
          <div className="goods-name">iPhone 12</div>
          <div className="goods-advantage">升维大提速</div>
          <div className="price-introduction">
            <div>RMB 229/月或 RMB 5499 起，</div>
            <div className="introduce">
              还可折抵换购<span className="shangbiao">1</span>
            </div>
          </div>
          <div className="buy-link">
            <a
              className="buy-link-text"
              href="https://www.apple.com.cn/iphone-12/"
            >
              进一步了解
            </a>
            <a href="https://www.apple.com.cn/iphone-12/">
              <div className="jiantou"></div>
            </a>
            <a
              className="buy-link-text"
              href="https://www.apple.com.cn/shop/buy-iphone/iphone-12"
            >
              购买
            </a>
            <a href="https://www.apple.com.cn/shop/buy-iphone/iphone-12">
              <div className="jiantou"></div>
            </a>
          </div>
        </div>
        <div className="goods" id="hero_ipad_pro">
          <div className="goods-name">iPhone 12</div>
          <div className="goods-advantage">由Apple M1 芯片强势驱动</div>
          <div className="buy-link">
            <a
              className="buy-link-text"
              href="https://www.apple.com.cn/iphone-12/"
            >
              进一步了解
            </a>
            <a href="https://www.apple.com.cn/iphone-12/">
              <div className="jiantou"></div>
            </a>
            <a
              className="buy-link-text"
              href="https://www.apple.com.cn/shop/buy-iphone/iphone-12"
            >
              购买
            </a>
            <a href="https://www.apple.com.cn/shop/buy-iphone/iphone-12">
              <div className="jiantou"></div>
            </a>
          </div>
        </div> */}
        <div className="goods-classify">
          <div className="classify-content">
            <div className="classify-item" id="promo_imac">
              {/* <div className="classify-item-title"></div>
              <div className="classify-item-content"></div>
              <div className="classify-item-link"></div> */}
            </div>
          </div>
          <div className="classify-content">
            <div className="classify-item" id="promo_watch">
              <div className="classify-item-title"></div>
              <div className="classify-item-content"></div>
              <div className="classify-item-link"></div>
            </div>
          </div>
        </div>
      </main>

      <footer className="footer">
        <div className="bottom">
          保留所有权利。
          <a href="#">隐私政策</a>
          <a href="#">| 使用条款</a>
          <a href="#">| 销售政策</a>
          <a href="#">| 法律信息</a>
          <a href="#">| 网站地图</a>
          {/* <br /> */}
          {/* 京公安网安备11010502008968 京ICP备10214630 营业执照
          无线电发射设备销售备案编号11201910351200 */}
        </div>
      </footer>
    </div>
  )
}
export default App
